### ISSUE TITLE
Is ESP8266 module (not D1 mini) 5V tolerant?

### ISSUE THREAD

**Issue by bilogic** [Hypfer/esp8266-vindriktning-particle-sensor#40]
Hi @Hypfer,

The readme says ESP8266 is 5V tolerant, is that true? i.e. I can connect 5V to ESP8266's 3.3V VDD
Or was it referring to the Wemos D1 mini being able to accept 5V?

Thanks!

**Comment by Hypfer** [comment]
https://github.com/Hypfer/esp8266-vindriktning-particle-sensor/issues/15#issuecomment-889892467
