### ISSUE TITLE
Not an issue but a suggestion: Merge into Esphome?

### ISSUE THREAD

**Issue by oopsitsaflame** [Hypfer/esp8266-vindriktning-particle-sensor#5]
Hi, would it be possible to get this device supported into esphome? I think it would fit quite good as a supported sensor and you would get all the other stuff esphome supports as a bonus.

**Comment by Hypfer** [comment]
@habbie already did that
See https://github.com/Hypfer/esp8266-vindriktning-particle-sensor/issues/3#issuecomment-882858203

Personally, I don't use ESPHome due to philosophical differences.

**Comment by Hypfer** [comment]
Just for reference, I'd like to mention that decentralization is a good thing.
We shouldn't be merging everything into a single yaml behemoth.

Nabu Casa is slowly eating the smarthome world which by definition is a bad thing even though their intentions are most likely good.
We need better solutions to eliminating boilerplate code than merging everything into a single legal entity.

**Comment by oopsitsaflame** [comment]
Just for reference too ;) I'd like to mention that while your concerns are understandable., I just like not having to rely on projects where I have to search half the internet for and then to discover that the one dude/duddette who  maintained it alone has last logged in 4 years ago. (not talking about you, but in general). Open source can help with both these problems but not eleminate them completely. 
https://xkcd.com/2347/
